---
- name: fix grub config
  copy:
    src: /boot/efi/EFI/centos/grubenv
    dest: /boot/grub2/grubenv
    remote_src: yes
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version|int == 8

- name: fix dns
  lineinfile:
    path: /etc/resolv.conf
    regexp: '^nameserver'
    line: 'nameserver 172.26.134.12'
- lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    regexp: '^DNS1'
    line: 'DNS1=172.26.134.12'
- lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    line: 'PEERDNS=no'

