# vim: et ts=2 sts=2 sw=2
---
all:
  vars:
    domain: cloud.cmats
    net_mgt: "{{ '172.26.134.0/24' | domain_net(name='net_mgt') }}"
  hosts:
#        172.26.134.20: {hostname: stg5vns3li}
#    172.26.134.21: {hostname: stg5res01li}
#    stg5res01li:
    dep: { mgt_ip: 4 }

  children:
    linux:
      children:
        cms:
          hosts:
            stg5CMSSSRV1: { mgt_ip: 17 }
        topsky:
          children:
            topsky_hmi:
              hosts:
                stg5hmi01li: { mgt_ip: 31 }
                stg5pil01li: { mgt_ip: 32 }
            topsky_dbm:
              hosts:
                stg5dbm01li: { mgt_ip: 22 }
#                172.26.134.23: {hostname: stg5dbm02li}
#            topsky_srv:
#              hosts:
#                172.26.134.24: {hostname: stg5srv01li} 
#                172.26.134.25: {hostname: stg5srv02li} 
#                172.26.134.26: {hostname: stg5srv03li} 
#        vns3:
#          hosts:
#            172.26.134.20: {hostname: stg5vns3li} 
    windows:
      hosts:
        testad1: { mgt_ip: 12 }

